esphome:
  name: pai-streamer
  friendly_name: pai-streamer
    
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

external_components:
  - source: github://oxan/esphome-stream-server
  
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pai-streamer"
    password: "pai-streamer"

captive_portal:

status_led:
  pin: GPIO2

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API

uart:
  id: uart_bus
  # add further configuration for the UART here
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO16
  # tx2 and rx2 UART2 - TX: GPIO16, RX: GPIO17 (Only on ESP32)

stream_server:
  uart_id: uart_bus
  # port: 1234

sensor:
  - platform: uptime
    name: Uptime Sensor

web_server:
  port: 80 
